### ISSUE TITLE
Core ML Support

### ISSUE THREAD

**Issue by 9SL9** [exPHAT/SwiftWhisper#13]
I noticed that Whisper cpp has coreml support:
https://github.com/ggerganov/whisper.cpp/tree/master#core-ml-support

Does SwiftWhisper support CoreML and if not, is this something I can setup to do in my project or does it require a change to SwiftWhisper?

**Comment by exPHAT** [comment]
@9SL9 Give this branch a try: https://github.com/exPHAT/SwiftWhisper/tree/coreml

The README explanation still needs some polishing, but you should be able to get up and running using that branch. The tests complete much faster so seems like it's working well. Going to merge into master in a few days.

**Comment by exPHAT** [comment]
Merged with #14
