### ISSUE TITLE
MLModelAsset: load failed with error

### ISSUE THREAD

**Issue by Eriice** [exPHAT/SwiftWhisper#15]
I've been following the whisper.cpp project to create the mlmodelc file. However, I've encountered an issue where the weights/weight.bin file, which is required by SwiftWhisper, is not being created. 

So when I run project with SwiftWhisper coreml, The exact error message I'm receiving is:
```
Could not open .../ggml-base-encoder.mlmodelc/weights/weight.bin
```
I'm not sure what I might be missing or doing incorrectly. Any guidance or suggestions would be greatly appreciated.

**Comment by exPHAT** [comment]
I also had issues generating the models myself. Instead I downloaded them from here: https://huggingface.co/ggerganov/whisper.cpp/tree/main

**Comment by Eriice** [comment]
> I also had issues generating the models myself. Instead I downloaded them from here: https://huggingface.co/ggerganov/whisper.cpp/tree/main

Thank you, with your help I successfully run the SwiftWhisper coreml project.
