### ISSUE TITLE
Add support for word-level timestamps `--word_timestamps`

### ISSUE THREAD

**Issue by martinlexow** [exPHAT/SwiftWhisper#17]
First of all: Thank you for coding this Swift Package — it’s terrific! 🙏

What I’m missing: I’d love to get **word-level timestamps** [like mentioned](https://huggingface.co/openai/whisper-large-v2#long-form-transcription) in the Whisper API.

For my understanding this would require that we can set `--word_timestamps` to `true`. (Maybe `WhisperParams` would be a good place for that?)

Keep up the great work!

Best, Martin

**Comment by martinlexow** [comment]
Just stumbled upon [this comment](https://github.com/ggerganov/whisper.cpp/issues/49#issuecomment-1301154359) where it says that using `--max-len 1` should result in word-level timestamps. 

However it seems to make no difference for me when setting `parameter.max_len = 1` — I still geht phrases/sentences.

**Comment by exPHAT** [comment]
Someone had asked about this in https://github.com/exPHAT/SwiftWhisper/issues/6 

Let me know if that works for you.

**Comment by martinlexow** [comment]
This indeed works pretty well — apologies for the duplicate!

    parameter.split_on_word = true
    parameter.max_len = 1
    parameter.token_timestamps = true
