### ISSUE TITLE
Is there a possibility to pause and resume transcription?

### ISSUE THREAD

**Issue by Eriice** [exPHAT/SwiftWhisper#18]
One approach that comes to mind is to record the current timestamp and re-truncate the audio for transcription, but that's not very elegant.

**Comment by exPHAT** [comment]
Unless whisper.cpp adds support for true pausing, that would be outside the scope of this project. 

I think your re-truncate approach would be fine. That's how I would do it personally.

**Comment by Eriice** [comment]
Thanks!
