### ISSUE TITLE
Running compiled C++ version of program is faster than using Library

### ISSUE THREAD

**Issue by iambenkay** [exPHAT/SwiftWhisper#19]
I expected that since the swift package uses the C++ code through interop, it would be just as fast. I did a test transcription using the same wav file and the base.en model. Running the main example from whisper cpp directly takes 2.7s to complete. The swift package takes >10s for the same model and wav file. Have no idea why it is happening. Can someone explain to me?

**Comment by exPHAT** [comment]
Have you read the speed boost section of the README?

**Comment by iambenkay** [comment]
Yes I had read it but it did not make my program any faster. Turns out I was decoding the wav file with number of channels set to 2 instead of 1 and that's why it was slow and hallucinating. My bad! I will close this issue now
