### ISSUE TITLE
unsafe build flags?

### ISSUE THREAD

**Issue by schlu** [exPHAT/SwiftWhisper#2]
I added SwiftWhisper as a SPM dependency, but I am getting an error about "unsafe build flags". I will try to track it down if I have time, but wanted to check if you know what it was?

<img width="1488" alt="Screenshot 2023-04-01 at 17 02 25" src="https://user-images.githubusercontent.com/5230/229301631-a0082acc-700d-42ea-8b33-fc2504820cd0.png">

**Comment by exPHAT** [comment]
It's used to get better optimization out of GGML when not compiling for a release target. You can work around this by specifying a specific commit hash for the build.

Example via `Package.swift`:
```swift
let package = Package(
    ...
    dependencies: [
        .package(url: "https://github.com/exPHAT/SwiftWhisper.git", exact: .init("8debb5710f7f334feb2febe519484b55b6173dc2")),
    ],
    ...
)
```

Example via Xcode (enter the commit hash `8debb5710f7f334feb2febe519484b55b6173dc2`):

![image](https://user-images.githubusercontent.com/7348226/229303162-e7d8cb9e-4ea7-4e1a-9abd-1531f1724c87.png)

**Comment by exPHAT** [comment]
Latest readme now details how to handle this
