### ISSUE TITLE
Do you have more boilerplate code (examples) to show an example of some application where the speech recognition is working?

### ISSUE THREAD

**Issue by shyamalschandra** [exPHAT/SwiftWhisper#20]
Do you have more boilerplate code (examples) to show an example of some application where the speech recognition is working?

**Comment by exPHAT** [comment]
You can check all of the tests I've written to view some more working examples. 

They're not using the async-await api (to preserve backwards compatibility with older Swift versions), but it should be enough to get you going.

**Comment by shyamalschandra** [comment]
Thank you, @exPHAT!  I will check it out and get back to you ASAP.

**Comment by exPHAT** [comment]
Did you find what you're looking for?

**Comment by shyamalschandra** [comment]
Still need to try it again!  Thanks!

**Comment by exPHAT** [comment]
I'm going to close this. Reopen it if you can't run the project.

**Comment by shyamalschandra** [comment]
Hi @exPHAT, do you have a example code with all the boilerplate to get started with using the CoreML model, the delegates, and the PCM Array to whisper.cpp STT?  Thanks, @shyamalschandra!
