### ISSUE TITLE
Missing required module 'whisper_cpp' when using the SwiftWhisper code.  

### ISSUE THREAD

**Issue by shyamalschandra** [exPHAT/SwiftWhisper#21]
<img width="1077" alt="Screenshot 2023-08-10 at 12 11 17 AM" src="https://github.com/exPHAT/SwiftWhisper/assets/9545735/2fb472d0-f145-4f65-a03d-7a617eabffcb">

How should I fix this problem to include the missing module whisper_cpp in the setup of the library for Swift because the other module is c++-based?  Thanks!

**Comment by exPHAT** [comment]
This is usually caused by Xcode being weird. If you pulled from GitHub make sure to initialize submodules. Otherwise try clearing your derived data and build folder.

**Comment by shyamalschandra** [comment]
Thank you!  I will check that out!

**Comment by exPHAT** [comment]
Any luck?

**Comment by exPHAT** [comment]
Closing for now. Let me know if this comes back up.

**Comment by metinaltinbas** [comment]
It still happens on extensions.
