### ISSUE TITLE
watchOS support?

### ISSUE THREAD

**Issue by haozes** [exPHAT/SwiftWhisper#23]
Need watchOS support. 

Best Regards

**Comment by exPHAT** [comment]
The watch surely doesn't meet the memory or processor requirements of these models.

**Comment by haozes** [comment]
Apple Watch 7 + series have 1GB+ RAM , It's enough to run whisper tiny model.  and I tried it, it works.
The only problem is the process, the transcribe time is too long (10 seconds wav need 6 sec on my Apple Watch Ultra)
Maybe supporting ANE / CoreML can reduce the time to 2-3 seconds.

**Comment by exPHAT** [comment]
If you want to try, CoreML is supported. Though I don't think any of the watches have ANE.

**Comment by haozes** [comment]
> If you want to try, CoreML is supported. Though I don't think any of the watches have ANE.
As this document says:
https://support.apple.com/en-il/HT213848

Apple Neural Engine
Available for: Apple Watch Series 4 and later

Not so much information about ANE on watch,  and I wil check it.

**Comment by haozes** [comment]
Hi, me again.

As I test by code:
https://developer.apple.com/documentation/coreml/mlcomputedevice/4134993-allcomputedevices
```
MLComputeDevice.allComputeDevices
```
That's cool, 
print on my ultra watch, it has 1 neuralEngine , and 2 GPU.

**Comment by exPHAT** [comment]
I'll fix the watchOS build and you can feel free to try running it.

**Comment by exPHAT** [comment]
watchOS build working in latest 1.2.0 release. Feel free to try now if you want to make something with it.
