### ISSUE TITLE
More boilerplate besides the test functions.

### ISSUE THREAD

**Issue by shyamalschandra** [exPHAT/SwiftWhisper#27]
Hi @exPHAT, do you have more example code with all the boilerplate to get started with using the CoreML model, the delegates, and the PCM Array to whisper.cpp STT? Thanks, @shyamalschandra!

I can do trial-and-error but it is much easier to have boilerplate.

**Comment by exPHAT** [comment]
[SwiftWhisperExample.zip](https://github.com/exPHAT/SwiftWhisper/files/12525104/SwiftWhisperExample.zip)

Here's a very basic example I made for you. Drag in any of the prebuilt models and call it `model.bin`.

You can also drag in a prebuilt core ML model with the correct name (as described in the README) and it will use that.

**Comment by shyamalschandra** [comment]
Hi @exPHAT,

I finally got the code working but it is really slow with tiny.en.bin.  Is this normal in Debug mode?  

Also, is WhisperDelegate implemented fully because I want to update my ProgressBar with the progress of the speech recognition?

Thank you again!

**Comment by exPHAT** [comment]
Yes. Please read the README for info about speed boosts. 

The delegate is fully implemented.
