### ISSUE TITLE
thoughts on reading from microphone data?

### ISSUE THREAD

**Issue by iloveitaly** [exPHAT/SwiftWhisper#28]
Any tips/tricks on how to tie in live microphone data into this library? Similar to the dictation system on macOS.

**Comment by aehlke** [comment]
see my fork, https://github.com/lake-of-fire/SwiftWhisperStream with discussion in the other issue thread here on streaming

**Comment by iloveitaly** [comment]
Awesome, thank you.

**Comment by exPHAT** [comment]
Closing in favour of https://github.com/exPHAT/SwiftWhisper/issues/4
