### ISSUE TITLE
missing required module whisper_cpp

### ISSUE THREAD

**Issue by Alchemy5** [exPHAT/SwiftWhisper#3]
I've tried using the master and fast version of this package in xcode and keep running into this issue with the message that I'm missing a required module called whisper_cpp. 
<img width="584" alt="image" src="https://user-images.githubusercontent.com/104028972/230492670-16b2d5eb-247b-4793-b64d-a5bb3fd32502.png">

Thank you!

**Comment by exPHAT** [comment]
How did you add SwiftWhipser to your project? Via Xcode's Swift Package manager, or via the `Package.swift` file?

If you've cloned the repo yourself, you'll need to make sure you initialize submodules when doing your `git clone`. You should be able to use `git clone --recurse-submodules https://github.com/exPHAT/SwiftWhisper.git` to make that happen.

**Comment by Alchemy5** [comment]
I used Xcode's Swift Package manager, so I didn't clone it myself.

Best,
Varun

**Comment by exPHAT** [comment]
Can you share which version of Xcode you're running? And macOS too?

I am able to create a fresh project and use the package just fine.

Perhaps also try clearing DerivedData, restarting Xcode, and trying to add it again.

**Comment by Alchemy5** [comment]
xcode version 14.2, macOS Ventura 13.2.1

Ok after clearing DerivedData and restarting it seems to be working.

Thank you!

**Comment by exPHAT** [comment]
Awesome. Will close this.
