### ISSUE TITLE
Split segment to words

### ISSUE THREAD

**Issue by chichiller** [exPHAT/SwiftWhisper#30]
At first thank you for your job
i have a question: when i transcribe audio file as PCM `[Float]` i receive as result `[Segment]`
i noticed that each Segment may contain not separate word, but sentence
how i can split sentence into separate words with timestamp for each?
I tried to use `WhisperParams` fields:
  1. max_len = 1
  2. split_on_word = true

but result always the same
The only thing is help me decrease words in sentence is using `beamSearch` strategy, but i still get sentence instead of separate words

my code
```
let params = WhisperParams(strategy: .beamSearch)
params.max_len = 1
params.split_on_word = true
whisper = Whisper(fromFileURL: modelUrl, withParams: params)
```

**Comment by exPHAT** [comment]
You can see the correct usage in https://github.com/exPHAT/SwiftWhisper/issues/6
