### ISSUE TITLE
large-v3

### ISSUE THREAD

**Issue by jacobjiangwei** [exPHAT/SwiftWhisper#32]
is there some new updates for tiny, medium model? Large doesn't work very well on mobile, I won't expect v3 can improve too much.

**Comment by exPHAT** [comment]
This package is purely focused on being a Swift wrapper over [whisper.cpp](https://github.com/ggerganov/whisper.cpp). If you have any model questions, I suggest you open an issue there as they'll likely be much more aware of what's coming down the pipe!
