### ISSUE TITLE
Diarization

### ISSUE THREAD

**Issue by roei46** [exPHAT/SwiftWhisper#36]
Hi!!
First of all great library! 
So thanks for that!
Second, is there an API  for diarization?

**Comment by exPHAT** [comment]
No, as far as I'm aware whisper.cpp (which this package is based on) doesn't support diarization itself. 

There seems to be an open issue [here](https://github.com/ggerganov/whisper.cpp/issues/525), but nothing has been officially added to whisper.cpp.
