### ISSUE TITLE
Split on word

### ISSUE THREAD

**Issue by 9SL9** [exPHAT/SwiftWhisper#6]
Firstly, thanks for sharing your library, it's great.

I'm trying to get a transcription that splits on each word. I understand (perhaps incorrectly) that to do this I need to set max_len=1 and split_on_word=true. Found here: https://github.com/ggerganov/whisper.cpp#word-level-timestamp

However I see no change in the segments in that they always seem to be split on the default/automatic settings. Please let me know if I'm doing something wrong. Here's my code:

```
let params = WhisperParams()
params.language = .english
params.max_len = 1
params.split_on_word = true

let whisper = Whisper(fromFileURL: Bundle.main.url(forResource: "ggml-tiny.en", withExtension: "bin")!, withParams: params)

let segments = try await whisper.transcribe(audioFrames: audioFrames)
transciption = segments.map(\.text).joined()
```

**Comment by exPHAT** [comment]
Looks like the whisper.cpp "[main](https://github.com/ggerganov/whisper.cpp/blob/master/examples/main/main.cpp#L770)" example sets `params.token_timestamps = true` when using the `max_len` argument.

You should be able to replace `split_on_word` with `token_timestamps` and get the desired output.

```swift
let params = WhisperParams()
params.language = .english
params.max_len = 1
params.token_timestamps = true
```

I've added a test case to the repo for this as well. You can find it [here](https://github.com/exPHAT/SwiftWhisper/commit/8d523f9791eb1c09b98256a5e2423762b7c09aeb).

**Comment by 9SL9** [comment]
Thanks that worked perfectly
