### ISSUE TITLE
CPU cost 400% always

### ISSUE THREAD

**Issue by jacobjiangwei** [exPHAT/SwiftWhisper#7]
Is there some interface expose outside to control the number of thread used? It takes 4 thread and always takes really long time to translate a couple of seconds audio. If we use more thread, leverage bio chip capability, would that be faster?

**Comment by exPHAT** [comment]
You can customize the number of threads used by setting `n_threads` for the whisper parameters.

```swift
let params = WhisperParams()
params.n_threads = 8

let whisper = Whisper(fromFileURL: /* ... */, withParams: params)

try await whisper.transcribe(/* ... */)
```

If you are finding transcription slow, remember to read the README completely. You can see [here](https://github.com/exPHAT/SwiftWhisper#speed-boost-rocket) where it talks about using the [`fast`](https://github.com/exPHAT/SwiftWhisper/tree/fast) branch based on commit hash to get higher performance when using `Debug` scheme.
