### ISSUE TITLE
Data about every word in each segment

### ISSUE THREAD

**Issue by eppee** [exPHAT/SwiftWhisper#8]
Is it possible to get time data for every word in each segment?

**Comment by exPHAT** [comment]
Yes, you can follow the same steps shown in this issue https://github.com/exPHAT/SwiftWhisper/issues/6

**Comment by eppee** [comment]
> Yes, you can follow the same steps shown in this issue #6

Thank you, I have however already tried. I should have been more clear.
It works great for continuous speaking audios.
But it works really bad when there are pauses in the speech, is there anything else than those parameterers I can work with?

**Comment by exPHAT** [comment]
Can you expand on this more? How does it work "really bad" for pauses in speech? What changes?

**Comment by eppee** [comment]
> Can you expand on this more? How does it work "really bad" for pauses in speech? What changes?

If I make a recording when continually speaking it works great. If I make a recording where I say something like
"Okay here I'm speaking about" and then I take a pause of like 10 seconds and continue. Then in that 10 second gap I expect it to not show any word but it does come words but in a slower pace. And if I stop speaking and then let it run for some seconds in the end it will also add words in that space.
Continuous speaking good
Breaks are filled with words and then accelerates back inte correct place when continuous speaking are reestablished

**Comment by exPHAT** [comment]
I haven't tested it, but have you looked into using `params.no_speech_thold`? Thats a value inside of whisper.cpp that is likely related to what you're looking for.

I don't think this is a bug inside of SwiftWhisper, so I'm going to keep this issue closed. Please re-open it if this a bug unique to this wrapper.

**Comment by eppee** [comment]
> I haven't tested it, but have you looked into using `params.no_speech_thold`? Thats a value inside of whisper.cpp that is likely related to what you're looking for.
> 
> I don't think this is a bug inside of SwiftWhisper, so I'm going to keep this issue closed. Please re-open it if this a bug unique to this wrapper.

Unfortunately it seems to make no difference. 
Its like it won't add any pauses at all actually.

In this example I make many long pauses, but as you can see the next word always starts where the previous ends. No gaps at all? Is this another parameter that I have forgotten?

0 - 120 : 
120 - 400 :  So
400 - 800 :  if
800 - 1420 :  I
1420 - 1790 :  make
1790 - 1990 :  a
1990 - 3000 :  video
3000 - 4980 :  and
4980 - 5580 :  if
5580 - 6570 :  I
6570 - 7040 :  take
7040 - 7160 :  a
7160 - 7360 :  long
7360 - 7620 :  pause
7620 - 7960 :  like
7960 - 10070 :  that

**Comment by exPHAT** [comment]
@eppee I haven't tested, but just released version 1.0.3 which uses the latest version of whisper.cpp. Might be worth checking if this is still a problem.

**Comment by eppee** [comment]
> @eppee I haven't tested, but just released version 1.0.3 which uses the latest version of whisper.cpp. Might be worth checking if this is still a problem.

Unfortunately there is no difference.
Been reading a lot and this seems to be a solution. But I don't know how to implement it in Swift...

https://github.com/openai/whisper/discussions/435
