### ISSUE TITLE
Progress delegate is not working

### ISSUE THREAD

**Issue by jacobjiangwei** [exPHAT/SwiftWhisper#9]
I tried, no call back.

If we check cpp code, it also didn't update anything to upper oc or swift layer.

// main loop
    while (true) {
        const int progress_cur = (100*(seek - seek_start))/(seek_end - seek_start);
        while (progress_cur >= progress_prev + progress_step) {
            progress_prev += progress_step;
            if (params.print_progress) {
                fprintf(stderr, "%s: progress = %3d%%\n", __func__, progress_prev);
            }
        }

How does it work? Does it even works?

**Comment by exPHAT** [comment]
> How does it work?

Does your audio have any words in it? Right now the progress delegate method is called based on last word time divided by total audio time. You can see that [here](https://github.com/exPHAT/SwiftWhisper/blob/master/Sources/SwiftWhisper/Whisper.swift#LL76).

> Does it even works?

Yes, I have a test case that validates all delegate methods are working. The test case expectation is [here](https://github.com/exPHAT/SwiftWhisper/blob/master/Tests/WhisperTests/Transcription%20Tests/TranscriptionTests.swift#L100).

I think whisper.cpp was updated to include a new `on_progress` callback, the submodule will need to be updated to the latest version to gain support for that. That would fix cases for recordings with no speech in them.

**Comment by jacobjiangwei** [comment]
it works, my bad. 
Thank you!
